--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 152, 152, 872, 872 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = QUATERNION( 0.008, -0.649, 0.007, 0.76 ),
                    ['position'] = VECTOR3( 677.5, 36.495, 416.5 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = QUATERNION( 0.008, -0.649, 0.007, 0.76 ),
                    ['position'] = VECTOR3( 346.5, 36.506, 607.5 ),
                },
                ['SoundEmitter_Skyhigh'] = {
                    ['EventName'] = STRING( 'SC2/SC2/Environments/SC2_MP_201/snd_SC2_MP_201_Skyhigh' ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Sound' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 512.5, 200, 512.5 ),
                },
                ['SoundEmitter_LandBridge'] = {
                    ['EventName'] = STRING( 'SC2/SC2/Environments/SC2_MP_201/snd_SC2_MP_201_Ocean_Shore' ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Sound' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 520.5, 43.371, 510.5 ),
                },
                ['SoundEmitter_OpenOcean_01'] = {
                    ['EventName'] = STRING( 'SC2/SC2/Environments/SC2_MP_201/snd_SC2_MP_201_Generic_Ocean' ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Sound' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 222.5, 33.999, 746.5 ),
                },
                ['SoundEmitter_OpenOcean_02'] = {
                    ['EventName'] = STRING( 'SC2/SC2/Environments/SC2_MP_201/snd_SC2_MP_201_Generic_Ocean' ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Sound' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 760.5, 34, 220.5 ),
                },
                ['gpnav Playable Island 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'gpnav Playable Island' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 377.5, 43.229, 680.5 ),
                },
                ['gpnav Playable Island 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'gpnav Playable Island' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 643.5, 43.222, 348.5 ),
                },
                ['gpnav Playable Island 03'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'gpnav Playable Island' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 486.5, 38.842, 371.5 ),
                },
                ['gpnav Playable Island 04'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'gpnav Playable Island' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 527.5, 38.841, 648.5 ),
                },
                ['gpnav Playable Island 05'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'gpnav Playable Island' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 522.5, 34, 565.5 ),
                },
                ['gpnav Playable Island 06'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'gpnav Playable Island' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 420.5, 33.999, 429.5 ),
                },
                ['Mass 01_mirrorXZ'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 688, 36.404, 421 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 336, 36.404, 603 ),
                },
                ['Mass 02_mirrorXZ'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 667, 36.401, 426 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 357, 36.401, 598 ),
                },
                ['Mass 03_mirrorXZ'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 668, 36.404, 408 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 356, 36.404, 616 ),
                },
                ['Mass 04_mirrorXZ'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 682, 36.435, 404 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 342, 36.444, 620 ),
                },
                ['Mass 05_mirrorXZ'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 668, 35.671, 464 ),
                },
                ['Mass 05'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 356, 35.671, 560 ),
                },
                ['Mass 06_mirrorXZ'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 612, 43.257, 484 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 410, 44.174, 538 ),
                },
                ['Mass 07_mirrorXZ'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 515, 38.842, 382 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 509, 38.842, 642 ),
                },
                ['Mass 08_mirrorXZ'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 719, 36.38, 477 ),
                },
                ['Mass 08'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 305, 36.38, 547 ),
                },
                ['Mass 09_mirrorXZ'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 683, 36.387, 624 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 341, 36.387, 400 ),
                },
                ['Mass 10_mirrorXZ'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 694, 36.388, 641 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 330, 36.388, 383 ),
                },
                ['SoundEmitter_Shore_02'] = {
                    ['EventName'] = STRING( 'SC2/SC2/Environments/SC2_MP_201/snd_SC2_MP_201_Generic_Ocean' ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Sound' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 524.5, 38.842, 655.5 ),
                },
                ['SoundEmitter_Shore_01'] = {
                    ['EventName'] = STRING( 'SC2/SC2/Environments/SC2_MP_201/snd_SC2_MP_201_Generic_Ocean' ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Sound' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 498.5, 38.842, 377.5 ),
                },
                ['Base Marker 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Base Marker' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 353.5, 36.478, 607.5 ),
                },
                ['Base Marker 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Base Marker' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 670.5, 36.468, 416.5 ),
                },
                ['Expansion Area 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 522.5, 38.841, 647.5 ),
                },
                ['Expansion Area 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 496.5, 38.842, 369.5 ),
                },
                ['Expansion Area 03'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 327.5, 36.479, 402.5 ),
                },
                ['Expansion Area 04'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 693.5, 36.468, 619.5 ),
                },
                ['Defensive Point 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 404.5, 44.206, 514.5 ),
                },
                ['Defensive Point 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 624.5, 43.284, 509.5 ),
                },
                ['Default Path Node 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 720.5, 36.469, 558.5 ),
                },
                ['Default Path Node 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 676.5, 37.231, 498.5 ),
                },
                ['Default Path Node 03'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 513.5, 43.371, 513.5 ),
                },
                ['Default Path Node 04'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 340.5, 36.478, 523.5 ),
                },
                ['Default Path Node 05'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 302.5, 36.478, 470.5 ),
                },
                ['Naval Area 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 346.5, 33.999, 463.5 ),
                },
                ['Naval Area 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 387.5, 33.999, 568.5 ),
                },
                ['Naval Area 03'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 673.5, 34, 567.5 ),
                },
                ['Naval Area 04'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 634.5, 33.999, 455.5 ),
                },
                ['Default Path Node 06'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 447.5, 34, 654.5 ),
                },
                ['Default Path Node 07'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 607.5, 34, 650.5 ),
                },
                ['Default Path Node 08'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 571.5, 33.999, 370.5 ),
                },
                ['Default Path Node 09'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 407.5, 33.999, 366.5 ),
                },
                ['Default Path Node 10'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 532.5, 34, 733.5 ),
                },
                ['Default Path Node 11'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 490.5, 33.999, 294.5 ),
                },
                ['Default Path Node 12'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 504.5, 33.999, 455.5 ),
                },
                ['Rally Point 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 338.5, 36.479, 554.5 ),
                },
                ['Rally Point 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 684.5, 36.468, 464.5 ),
                },
                ['Naval Rally Point 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Naval Rally Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 588.5, 33.999, 441.5 ),
                },
                ['Naval Rally Point 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Naval Rally Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 638.5, 34, 581.5 ),
                },
                ['Naval Rally Point 03'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Naval Rally Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 425.5, 33.999, 591.5 ),
                },
                ['Naval Rally Point 04'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Naval Rally Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 385.5, 33.999, 434.5 ),
                },
                ['Effect 01'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water01' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 451.5, 28, 537.5 ),
                },
                ['Effect 02'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water01' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 471.157, 28, 538.604 ),
                },
                ['Effect 03'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water01' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 490.759, 28, 538.385 ),
                },
                ['Effect 04'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water01' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 509.921, 28, 538.17 ),
                },
                ['Effect 05'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water01' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 529.601, 28, 538.284 ),
                },
                ['Effect 06'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water01' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 548.804, 28, 538.323 ),
                },
                ['Effect 07'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water01' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 567.5, 28, 538.5 ),
                },
                ['Effect 08'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water02' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, -1, 0, 0 ),
                    ['position'] = VECTOR3( 567.5, 28, 482.063 ),
                },
                ['Effect 09'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water02' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, -1, 0, 0 ),
                    ['position'] = VECTOR3( 548.5, 28, 482.077 ),
                },
                ['Effect 10'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water02' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, -1, 0, 0 ),
                    ['position'] = VECTOR3( 529.5, 28, 482.216 ),
                },
                ['Effect 11'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water02' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, -1, 0, 0 ),
                    ['position'] = VECTOR3( 509.5, 28, 482.509 ),
                },
                ['Effect 12'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water02' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, -1, 0, 0 ),
                    ['position'] = VECTOR3( 491.5, 28, 482.111 ),
                },
                ['Effect 13'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water02' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, -1, 0, 0 ),
                    ['position'] = VECTOR3( 471.143, 28, 481.972 ),
                },
                ['Effect 14'] = {
                    ['EmitterTemplate'] = STRING( 'MP201Water02' ),
                    ['EmitterScale'] = FLOAT( 1.0 ),
                    ['EmitterOffset'] = VECTOR3( 0, 0, 0 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Effect' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, -1, 0, 0 ),
                    ['position'] = VECTOR3( 451.5, 28, 482.114 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    Armies =  
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_EXTRA'] =  
        {
            personality = '',
            plans = '',
            ['color'] = FLOAT( 1.0 ),
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                Units = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            ['color'] = FLOAT( 1.0 ),
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                Units = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            ['color'] = FLOAT( 1.0 ),
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                Units = {
                },
            },
        },
    },
}
