--*****************************************************************************
--* File: lua/modules/ui/lobby/ainames.lua
--* Author: Chris Blackwell
--* Summary: Contains a list of names the AI can assign to units
--*
--* Copyright © 2006 Gas Powered Games, Inc.  All rights reserved.
--*****************************************************************************

ainames = {
    uef = {
        "Maddox",
        "Daxil",
        "Rodgers",
        "Coleman",
        "Riley",
        "Fletcher",
        "Aiko",
        "Clarke",
        "Hall",
        "Arnold",
        "Graham",
        "Lundquist",
        "TheContact",
        "Bander",
        "Sanctuary",
        "Mr. Cow",
        "Hawthorne",
        "Prince Pablo",
		"Jaws2002",
    },
    cybran = {
        "Brackman",
        "Gauge",
        "Dostya",
        "Hex5",
        "Daroza",
        "Servo",
        "Lucas",
        "Hendiesel",
        "Evil Dr. Larry",
        "Dox",
        "Sorian",
        "Swanny500",
        "Finntabulous",
        "Audrey",
        "Pugtato",
        "MolotovRocket",
        "Halcyon",
		"Guillem",
    },
    illuminate = {
        "Kael",
        "Burke",
        "Marxon",
        "Toth",
        "Rhiza",
        "Smith",
        "Toth",
        "Amalia",
        "Celene",
        "Gari",
        "Sleepy",
        "Iziin",
        "Maxabillion",
        "OverBrainz",
        "Eric",
        "Rogue",
        "Wolfe",
        "Bimos",
    },
}