X360FontData = {
	{ base_family = "Arial", location = "/fonts/x360/xarial.xtf" },
	{ base_family = "Arial Bold", location = "/fonts/x360/xarial.xtf" },
	{ base_family = "Arial Narrow Regular", location = "/fonts/x360/xarial.xtf" },
	{ base_family = "Zeroes Two", location = "/fonts/x360/xzeroes_2.xtf" },
	{ base_family = "Zeroes Three", location = "/fonts/x360/xzeroes_3.xtf" },
	{ base_family = "Andale Mono", location = "/fonts/x360/xarial.xtf" },
	{ base_family = "Enigmatic Unicode Regular", location = "/fonts/x360/EnigmaU_2.xtf" },
	{ base_family = "Enigmatic Unicode Bold", location = "/fonts/x360/EnigmaBD.xtf" },
	{ base_family = "Enigmatic Unicode Italic", location = "/fonts/x360/EnigmaI.xtf" },
    { base_family = "Enigmatic Bold", location = "/fonts/x360/EnigmaBD.xtf" },
    { base_family = "FuturaLightTT", location = "/fonts/x360/FTR35__U.xtf" },
    { base_family = "FuturaMediumTT", location = "/fonts/x360/FTR55__U.xtf" },
    { base_family = "FuturaDemiTT", location = "/fonts/x360/FTR65__U.xtf" },
    { base_family = "MagistralTT", location = "/fonts/x360/MGS45__U.xtf" },
    { base_family = "MagistralTT Bold", location = "/fonts/x360/MGS65__U.xtf" },
    { base_family = "MagistralBlackTT", location = "/fonts/x360/MGS85__U.xtf" },
}

X360FontData_JP = {
	{ base_family = "Arial", location = "/fonts/x360/TBGM.xtf" },
	{ base_family = "Arial Bold", location = "/fonts/x360/TBGM.xtf" },
	{ base_family = "Arial Narrow Regular", location = "/fonts/x360/TBGM.xtf" },
	{ base_family = "Zeroes Two", location = "/fonts/x360/TBGM.xtf" },
	{ base_family = "Zeroes Three", location = "/fonts/x360/TBGM.xtf" },
	{ base_family = "Andale Mono", location = "/fonts/x360/TBGM.xtf" },
	{ base_family = "Enigmatic Unicode Regular", location = "/fonts/x360/TBGM.xtf" },
	{ base_family = "Enigmatic Unicode Bold", location = "/fonts/x360/TBGM.xtf" },
	{ base_family = "Enigmatic Unicode Italic", location = "/fonts/x360/TBGM.xtf" },
    { base_family = "Enigmatic Bold", location = "/fonts/x360/TBGM.xtf" },
    { base_family = "FuturaLightTT", location = "/fonts/x360/TBGM.xtf" },
    { base_family = "FuturaMediumTT", location = "/fonts/x360/TBGM.xtf" },
    { base_family = "FuturaDemiTT", location = "/fonts/x360/TBGM.xtf" },
    { base_family = "MagistralTT", location = "/fonts/x360/TBGM.xtf" },
    { base_family = "MagistralTT Bold", location = "/fonts/x360/TBGM.xtf" },
    { base_family = "MagistralBlackTT", location = "/fonts/x360/TBGM.xtf" },
}