--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 212.5, 322.475, 812.5, 786.526 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = QUATERNION( 0.008, -0.649, 0.007, 0.76 ),
                    ['position'] = VECTOR3( 349.5, 110.046, 554.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = QUATERNION( 0.011, -0.326, 0.004, 0.945 ),
                    ['position'] = VECTOR3( 676.5, 110.008, 554.5 ),
                },
                ['SoundEmitter_Factory_02'] = {
                    ['EventName'] = STRING( 'SC2/SC2/Environments/SC2_MP_101/snd_SC2_MP_101_Factory_Rumble' ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Sound' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 814.5, 163.006, 548.5 ),
                },
                ['SoundEmitter_Factory_01'] = {
                    ['EventName'] = STRING( 'SC2/SC2/Environments/SC2_MP_101/snd_SC2_MP_101_Factory_Rumble' ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Sound' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 213.5, 163.006, 548.5 ),
                },
                ['SoundEmitter_Skyhigh'] = {
                    ['EventName'] = STRING( 'SC2/SC2/Environments/SC2_MP_101/snd_SC2_MP_101_Skyhigh' ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Sound' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 512.5, 200, 512.5 ),
                },
                ['Mass 01_mirrorX'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 704, 110.277, 523 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 320, 110.313, 523 ),
                },
                ['Mass 02_mirrorX'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 665, 109.988, 565 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 359, 109.988, 565 ),
                },
                ['Mass 03_mirrorX'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 665, 110, 546 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 359, 110, 546 ),
                },
                ['Mass 04_mirrorX'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 659, 116.186, 414 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 365, 116.186, 414 ),
                },
                ['Mass 05_mirrorX_mirrorX'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 417, 110.208, 477 ),
                },
                ['Mass 05_mirrorX'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 607, 110.208, 477 ),
                },
                ['Mass 06_mirrorX'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 609, 116.186, 535 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 415, 116.185, 535 ),
                },
                ['Mass 07_mirrorX'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 680, 110.06, 659 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 344, 110.06, 659 ),
                },
                ['Mass 10_mirrorX'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 536, 110.159, 698 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 488, 110.16, 698 ),
                },
                ['Mass 09_mirrorX'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 686, 110.021, 565 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 6.0 ),
                    ['amount'] = FLOAT( 100.0 ),
                    ['resource'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 338, 110.021, 565 ),
                },
                ['Base Marker 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Base Marker' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 679.5, 110.036, 523.5 ),
                },
                ['Base Marker 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Base Marker' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 339.5, 110.08, 530.5 ),
                },
                ['Expansion Area 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 512.5, 110.192, 726.5 ),
                },
                ['Defensive Point 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 705.5, 110.091, 672.5 ),
                },
                ['Defensive Point 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 587.5, 107.61, 514.5 ),
                },
                ['Defensive Point 03'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 319.5, 110.089, 673.5 ),
                },
                ['Rally Point 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 638.5, 110.016, 511.5 ),
                },
                ['Rally Point 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 386.5, 110.018, 512.5 ),
                },
                ['Defensive Point 04'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 437.5, 107.494, 513.5 ),
                },
                ['Defensive Point 05'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 512.5, 116.22, 554.5 ),
                },
                ['Defensive Point 06'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 512.5, 116.22, 653.5 ),
                },
                ['Default Path Node 01'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 511.5, 116.22, 610.5 ),
                },
                ['Default Path Node 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 512.5, 109.886, 429.5 ),
                },
                ['Default Path Node 03'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 467.5, 102.98, 433.5 ),
                },
                ['Default Path Node 04'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 558.5, 103.18, 437.5 ),
                },
                ['Default Path Node 05'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 466.5, 105.433, 610.5 ),
                },
                ['Default Path Node 06'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 557.5, 105.434, 609.5 ),
                },
                ['Default Path Node 07'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 462.5, 106.411, 512.5 ),
                },
                ['Default Path Node 08'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 353.5, 116.219, 450.5 ),
                },
                ['Default Path Node 09'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 353.5, 109.887, 480.5 ),
                },
                ['Default Path Node 10'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 353.5, 110.093, 627.5 ),
                },
                ['Default Path Node 11'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 386.5, 109.537, 533.5 ),
                },
                ['Default Path Node 12'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 407.5, 110.377, 495.5 ),
                },
                ['Default Path Node 13'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 437.5, 116.22, 493.5 ),
                },
                ['Default Path Node 14'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 437.5, 116.22, 455.5 ),
                },
                ['Default Path Node 15'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 422.5, 116.219, 535.5 ),
                },
                ['Default Path Node 16'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 390.5, 116.22, 571.5 ),
                },
                ['Default Path Node 17'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 319.5, 110.059, 727.5 ),
                },
                ['Default Path Node 18'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 705.5, 110.059, 727.5 ),
                },
                ['Default Path Node 19'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 672.5, 110.093, 627.5 ),
                },
                ['Default Path Node 20'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 634.5, 116.22, 574.5 ),
                },
                ['Default Path Node 21'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 602.5, 116.219, 535.5 ),
                },
                ['Default Path Node 22'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 637.5, 109.518, 533.5 ),
                },
                ['Default Path Node 23'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 619.5, 110.022, 494.5 ),
                },
                ['Default Path Node 24'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 586.5, 116.22, 455.5 ),
                },
                ['Default Path Node 25'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 671.5, 116.219, 450.5 ),
                },
                ['Default Path Node 26'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 669.5, 110.418, 479.5 ),
                },
                ['Default Path Node 27'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 319.5, 110.093, 617.5 ),
                },
                ['Default Path Node 28'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 705.5, 110.093, 616.5 ),
                },
                ['Default Path Node 29'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 587.5, 116.22, 493.5 ),
                },
                ['Default Path Node 30'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 556.5, 106.35, 512.5 ),
                },
                ['Expansion Area 02'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 679.5, 116.22, 431.5 ),
                },
                ['Expansion Area 03'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 344.5, 116.22, 433.5 ),
                },
                ['Default Path Node 31'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 430.5, 105.457, 595.5 ),
                },
                ['Default Path Node 32'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 589.5, 105.476, 593.5 ),
                },
                ['Default Path Node 33'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 636.5, 116.22, 626.5 ),
                },
                ['Default Path Node 34'] = {
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Default Path Node' ),
                    ['prop'] = STRING( '' ),
                    ['orientation'] = QUATERNION( 0, 0, 0, 1 ),
                    ['position'] = VECTOR3( 388.5, 116.22, 626.5 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    Armies =  
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_EXTRA'] =  
        {
            personality = '',
            plans = '',
            ['color'] = FLOAT( 1.0 ),
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                Units = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            ['color'] = FLOAT( 1.0 ),
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                Units = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            ['color'] = FLOAT( 1.0 ),
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                Units = {
                },
            },
        },
    },
}
